### ISSUE TITLE
Relay fetch is not defined

### ISSUE THREAD

**Issue by idkjs** [jscomplete/reactful#1]
Im trying to get Relay to work with reactful but keep getting 'fetch is not defined'. If I import fetch into Environment.js the error turns into 'fetch is not a function'. My hunch is that I need to use something like https://github.com/denvned/isomorphic-relay to get it going. Any experience with this? Any guidance? Thank you.

**Comment by samerbuna** [comment]
The npm fetch package is not what you need. The package that implements the fetch API is isomorphic-fetch
