### ISSUE TITLE
Deploying to production

### ISSUE THREAD

**Issue by scottys88** [jscomplete/reactful#16]
HI there,

I took your course on PluralSight which was excellent thank you. I have now used the Reactful package to build and app. I am trying to deploy i. I'm unfamiliar with pm2.

I have tried to deploy it to Heroku but not having any luck. I am wondering if you have any advice on deploying this package into a hosting environment and which you might recommend? 

Thanks

**Comment by esteban89** [comment]
Hey, could you deploy? I'm exactly where you are, I run build:all and don't know what else to do, and no index.html file is generated

**Comment by scottys88** [comment]
@esteban89 , I was going around in circles so I ended up converting to `create-react-app` and my own express server. Server side rendering was not really important for me so I could do without it and it's been much smoother for me.

**Comment by esteban89** [comment]
@scottys88 Thanks, guess I'll do the same

**Comment by mattliu-mygit** [comment]
Dear friends,

Has there been an update on resources to deploy a reactful app? 
I've been trying to deploy an app I created in a couple of different platforms, and I now have a face-shaped indent on my keyboard.

Best,

**Comment by samerbuna** [comment]
Apologies for the lack of documentation on this.

To deploy a default Reactful app in production your deployment flow needs to run the script build:all and then run the script prod:start. 

The prod:start script runs one or more node processes (pm2) on the port of your choosing. Your provider has to support hosting a node process.

It's not recommended that you run the node process on port 80. Run a web server like nginx on 80, serve all your static assets through it, and proxy it to the pm2 port for the rest.
