### ISSUE TITLE
React version not specified in eslint-plugin-react settings

### ISSUE THREAD

**Issue by area73** [jscomplete/reactful#6]
When I try to run yarn eslint  or yarn format amongst others I always get this message:

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration 

I follow this Issue:
https://github.com/yannickcr/eslint-plugin-react/issues/1955

And they suggest to use "version": "detect"  on configuration file.

If you look at https://github.com/yannickcr/eslint-plugin-react#configuration you can see how they are adding that configuration , but I don't know if we need to add all that config or your intention is to handle that warning in a different way.

Thanks

**Comment by samerbuna** [comment]
It's probably okay to add the detect configuration. I'll look into it.

Thanks for reporting this!
